### ISSUE TITLE
Feature Request: Select Image override on posts (versus image sets)

### ISSUE THREAD

**Issue by joelgoodman** [Moqume/Background-Manager-WP#11]
Could the background override panel on posts and pages be modified to select a single image versus an entire image set? 

For instance, on my portfolio I'd like to use a different static image as the background for each portfolio post. As the plugin stands I must create a new image set for each post and fill it with one image.

It would be **fantastic** if I could choose an image from the media library (or from a background images set) to use. That way I could have one background set called "Portfolio" with an image for each.

Haven't looked through the plugin code too thoroughly, but thought I'd bring this up before I forget.

**Comment by Moqume** [comment]
This isn't something I would consider, given there are other plugins that provide this functionality. However, if there are more similar requests, I'd be happy to reconsider that.

**Comment by joelgoodman** [comment]
Understandable. I'd just rather not have to run two plugins when yours is the best for random image loading. Maybe I just need to fork it or roll my own. Thought I'd try here before doing that myself and was hoping you'd give me a reason to keep using the plugin and make a donation. Thanks anyway.
