### ISSUE TITLE
slideshow in IE

### ISSUE THREAD

**Issue by geertbaven** [Moqume/Background-Manager-WP#6]
Does the backgroundslideshow work in IE8?

**Comment by Moqume** [comment]
It does - or at least, it is supposed to ;) Is this related to the report at WordPress (http://wordpress.org/support/topic/plugin-background-manager-slideshow-not-working-on-frontpage-with-windows-xp)? I'll look into it.

**Comment by geertbaven** [comment]
yes Michael, I have made two postings on this; github and wordpress forum.
The slideshow option is not working on the homepage in windows XP IE8 and
Chrome. Thanks for looking into this
cheers
Geert

Op 20 februari 2012 18:46 schreef Michael Green <
reply@reply.github.com

> het volgende:
> 
> It does - or at least, it is supposed to ;) Is this related to the report
> at WordPress (
> http://wordpress.org/support/topic/plugin-background-manager-slideshow-not-working-on-frontpage-with-windows-xp)?
> I'll look into it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/Myatu/Background-Manager-WP/issues/6#issuecomment-4058249

## 

twitter.com/geertbaven
http://twitter.com/geertbaven
www.strikingconcepts.nl

http://www.strikingconcepts.nlhttp://www.linkedin.com/in/geertbaven

Postbus 1104 9701 BC Groningen

**Comment by Moqume** [comment]
Will push out a fix here in just a few moments, then forward it through WordPress.
